const MOBILE_CARDS_VALUE = 5;
const TABLET_CARDS_VALUE = 8;
const DESCTOP_CARDS_VALUE = 12;

const SET_MOBILE_CARDS_VALUE = 2;
const SET_TABLET_CARDS_VALUE = 2;
const SET_DESCTOP_CARDS_VALUE = 3;

const MOBILE_CARDS_SIZE = 480;
const TABLET_CARDS_SIZE = 768;
const DESCTOP_CARDS_SIZE = 1280;

const SHORT_MOVIE_TIME_LIMIT = 40;

export {
	MOBILE_CARDS_VALUE,
	TABLET_CARDS_VALUE,
	DESCTOP_CARDS_VALUE,

	SET_MOBILE_CARDS_VALUE,
	SET_TABLET_CARDS_VALUE,
	SET_DESCTOP_CARDS_VALUE,

	MOBILE_CARDS_SIZE,
	TABLET_CARDS_SIZE,
	DESCTOP_CARDS_SIZE,

	SHORT_MOVIE_TIME_LIMIT,
};